<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Marten" />
    <PackageReference Include="Marten" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../MESNET.Common.Infrastructure/MESNET.Common.Infrastructure.csproj" />
    <ProjectReference Include="../../../MESNET.Common.Shared/MESNET.Common.Shared.csproj" />
    <ProjectReference Include="../MESNET.Contract.Core/MESNET.Contract.Core.csproj" />
    <ProjectReference Include="../MESNET.Contract.Shared/MESNET.Contract.Shared.csproj" />
    <ProjectReference Include="../../Institution/MESNET.Institution.Shared/MESNET.Institution.Shared.csproj" />
  </ItemGroup>

</Project>
