<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Keycloak.AuthServices.Authorization" />
    <PackageReference Include="Marten" />
    <PackageReference Include="Minio" />
    <PackageReference Include="Mjml.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MESNET.Common.Shared/MESNET.Common.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Email/Templates/**/*.mjml" />
    <EmbeddedResource Include="Email/Assets/**/*" />
  </ItemGroup>

</Project>
