<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.NodeJs" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MESNET.Presentation/MESNET.Presentation.csproj" />
    <ProjectReference Include="../MESNET.Seeder/MESNET.Seeder.csproj" />
  </ItemGroup>

</Project>
