<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Marten" />
    <PackageReference Include="Marten" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MESNET.Attendance.Core/MESNET.Attendance.Core.csproj" />
    <ProjectReference Include="../MESNET.Attendance.Shared/MESNET.Attendance.Shared.csproj" />
    <ProjectReference Include="../../Institution/MESNET.Institution.Shared/MESNET.Institution.Shared.csproj" />
    <ProjectReference Include="../../Enrollment/MESNET.Enrollment.Shared/MESNET.Enrollment.Shared.csproj" />
    <ProjectReference Include="../../Security/MESNET.Security.Shared/MESNET.Security.Shared.csproj" />
    <ProjectReference Include="../../../MESNET.Common.Infrastructure/MESNET.Common.Infrastructure.csproj" />
  </ItemGroup>

</Project>
