<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MESNET.Attendance.Application/MESNET.Attendance.Application.csproj" />
    <ProjectReference Include="../MESNET.Attendance.Persistence/MESNET.Attendance.Persistence.csproj" />
  </ItemGroup>

</Project>
